### ISSUE TITLE
https://github.com/akirak/orgabilize.el fails in orgabilize but succeeds in readability-cli

### ISSUE THREAD

**Issue by analyticd** [akirak/orgabilize.el#4] opened 2022-05-12 14:39 UTC
Thanks for the package, I am trying it out. Ran into this issue (but don't run into it with same URL from cli) with M-x  orgabilize-insert-org-toc:

```
(Added to ~/dotfiles/emacs/var/orgabilize/cache/github.com_akirak_orgabilizeel__33c1ca0822.html
orgabilize--run-readable: Readable failed on https://github.com/akirak/orgabilize.el: Reading...
Processing...
[0m[1m[31merror[0m: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')
	    const p = document.createElement("p");
[0m[31m	                       ^[0m
    at [0m[1m[3mescapeHTML[0m ([0m[36mfile:///~/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs[0m:[0m[33m402[0m:[0m[33m25[0m)
    at [0m[36mfile:///~/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs[0m:[0m[33m58[0m:[0m[33m11[0m
    at [0m[1m[3mdefault[0m ([0m[36mfile:///~/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs[0m:[0m[33m472[0m:[0m[33m20[0m)
    at async [0m[36mfile:///~/.ghq/gitlab.com/gardenappl/readability-cli/readable.ts[0m:[0m[33m113[0m:[0m[33m1[0m

Added to ~/dotfiles/emacs/var/orgabilize/fetch.log)

```

Note that I've altered the paths in the log output above to use ~ rather than an absolute path.

Also here is my orgabilize config:

```
;; Precondition: install deno
;; Precondition: chmod +x readable.ts
;; Use Firefox reader view cli usage for cleaner (yet less resilient
;; to invalid HTML than org-web-tools) web page views inside org.
;; Source: https://github.com/akirak/orgabilize.el
(use-package orgabilize
  :straight (:host github :repo "akirak/orgabilize.el")
  :init
  (setq orgabilize-cache-directory (expand-file-name "orgabilize/cache" "~/dotfiles/emacs/var")
        orgabilize-fetch-log-file
        (expand-file-name "orgabilize/fetch.log" "~/dotfiles/emacs/var")
        orgabilize-executable (expand-file-name "readable.ts" (ghq-path "gitlab.com/gardenappl/readability-cli")) ))
```

Note that I had to set some variables due to using straight as a package manager and requirements of my unique config.

**Comment by akirak** [comment] 2022-05-13 01:15
Thank you for reporting this issue. 

It seems that the issue is on the JavaScript side. Can you check if the following command succeeds? (The issue may be dependent on options, so please try it with the exact options):

```sh
readable --json --keep-classes URL
```

If the command successfully runs, then please paste the URL causing the error.

**Comment by analyticd** [comment] 2022-05-14 04:18
I show all four possible cases/permutations of command invocation using readability-cli switches you provided:

1) here is the command that you requested and its output:

❯ ~/.ghq/gitlab.com/gardenappl/readability-cli/readable.ts  --json --keep-classes  https://github.com/akirak/orgabilize.el
Retrieving...
Processing...
```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')
            const p = document.createElement("p");
                               ^
    at escapeHTML (file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs:402:25)
    at file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs:58:11
    at default (file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs:472:20)
    at async file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/readable.ts:113:1

```

2) then when I do it without the readability switches (it works fine):

```
❯ ~/.ghq/gitlab.com/gardenappl/readability-cli/readable.ts    https://github.com/akirak/orgabilize.el
Retrieving...
Processing...
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="chrome://global/skin/aboutReader.css" type="text/css">
  <title>GitHub - akirak/orgabilize.el: (WIP) Convert web pages to readable Org</title>
</head>

<body class="light sans-serif loaded" style="--font-size:14pt; --content-width:40em;">
  <div class="container" >
    <div class="header reader-header reader-show-element">
      <h1 class="reader-title">GitHub - akirak/orgabilize.el: (WIP) Convert web pages to readable Org</h1>
      <div class="credits reader-credits">akirak</div>
    </div>
etc...
```
 Now let's check with each switch in isolation for completeness:

3) With just --keep-classes (works fine):
```
❯ ~/.ghq/gitlab.com/gardenappl/readability-cli/readable.ts  --keep-classes  https://github.com/akirak/orgabilize.el
Retrieving...
Processing...
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>GitHub - akirak/orgabilize.el: (WIP) Convert web pages to readable Org</title>
</head>

<body>
<h1>GitHub - akirak/orgabilize.el: (WIP) Convert web pages to readable Org</h1>

<hr>
<div><div>
etc...
```

4) and with only the --json flag (this is the actual problem: the --json flag):

```
❯ ~/.ghq/gitlab.com/gardenappl/readability-cli/readable.ts  --json  https://github.com/akirak/orgabilize.el
Retrieving...
Processing...
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')
            const p = document.createElement("p");
                               ^
    at escapeHTML (file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs:402:25)
    at file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs:58:11
    at default (file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/common.mjs:472:20)
    at async file:///Users/foobar/.ghq/gitlab.com/gardenappl/readability-cli/readable.ts:113:1

```

**Comment by akirak** [comment] 2022-05-14 05:47
Then it is an issue with readability. It has nothing to do with this package, so I will close this issue.

**Closed as completed by akirak** 2022-05-14 05:47 UTC
